"""
utils.py

Token estimation and the marker-file mechanism that lets this tool tag
its own generated output so future scans never re-ingest it as source.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

from .constants import GENERATED_MARKER_FILENAME

_TIKTOKEN_ENCODER = None
_TIKTOKEN_AVAILABLE = importlib.util.find_spec("tiktoken") is not None


def estimate_tokens(text: str) -> tuple[int, str]:
    global _TIKTOKEN_ENCODER
    if _TIKTOKEN_AVAILABLE:
        if _TIKTOKEN_ENCODER is None:
            import tiktoken

            _TIKTOKEN_ENCODER = tiktoken.get_encoding("cl100k_base")
        return len(_TIKTOKEN_ENCODER.encode(text)), "tiktoken cl100k_base"
    return max(1, len(text) // 4), "approx, chars/4 -- install tiktoken for exact count"


def write_generated_marker(directory: Path) -> None:
    try:
        (directory / GENERATED_MARKER_FILENAME).write_text(
            "This directory was generated by project-context. Safe to delete; "
            "automatically excluded from future scans.\n",
            encoding="utf-8",
        )
    except OSError:
        pass


def dir_has_generated_marker(directory: Path) -> bool:
    return (directory / GENERATED_MARKER_FILENAME).exists()
